# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: goserver
  pullPolicy: Never
  containerPort: 3333
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

environment:
  name: "prd"