apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: hello
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
        - name: the-container
          image: e2e-test-images/agnhost:2.39
          command: ["/agnhost", "netExec"]
          ports:
            - containerPort: 8080
