kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    environment: {{ .Values.environment.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      deployment: hello
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
        - name: the-container
          image: {{ .Values.image.repository }}
          args: ["-listen=:8080", "-text='hello world'"]
          ports:
            - containerPort: 8080
