kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    environment: {{ .Values.environment.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      deployment: hello
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
        - name: {{ .Values.image.repository }}-container
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.image.containerPort }}
          env:
            - name: MONGODB_URI
              value: mongodb://{{ .Release.Name }}-mongodb:27017
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.image.containerPort }}
              httpHeaders:
                - name: X-Requested-By
                  value: readinessProbe
            initialDelaySeconds: 5
            periodSeconds: 500
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.image.containerPort }}
              httpHeaders:
                - name: X-Requested-By
                  value: livenessProbe
            initialDelaySeconds: 5
            periodSeconds: 30
