kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    environment: {{ .Values.environment.name }}
spec:
  selector:
    deployment: hello
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8666
      targetPort: 8080
