apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: hello
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
        - name: the-container
          image: hashicorp/http-echo
          args: ["-listen=:8080", "-text='hello world'"]
          ports:
            - containerPort: 8080
