name: PR Checks

on:
  pull_request:

jobs:
  test-server:
    runs-on: ubuntu-latest
    container: vektra/mockery
    env:
      WORKING_DIR: ./packages/server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.WORKING_DIR }}/go.mod
      - name: Unit Test
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          apk add make
          make test
