name: PR Checks

on:
  pull_request:

jobs:
  test-server:
    runs-on: ubuntu-latest
    container: vektra/mockery
    env:
      WORKING_DIR: ./packages/server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.WORKING_DIR }}/go.mod
      - name: Unit Test
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          apk add make
          make test
  k8s-lint:
    runs-on: ubuntu-latest
    env:
      TEMPLATE_OUTPUT: ./template_out
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Run Helm Template
        run: helm template ./packages/helm --output-dir ${{ env.TEMPLATE_OUTPUT }} --namespace namespace --set environment.name=actions
      - name: Lint K8s YAMLs
        uses: stackrox/kube-linter-action@v1
        with:
          directory: ${{ env.TEMPLATE_OUTPUT }}

